### ISSUE TITLE
Example results in a kernel crash due to multiple instances of the OpenMP library libiomp5md.dll loaded

### ISSUE THREAD

**Issue by mattslezak-shell** [cmdty/storage#13]
The easy fix for this is just a simple:

    import os
    os.environ['KMP_DUPLICATE_LIB_OK']='True'

Anyhow, on an Anaconda Python installation you get a crash from multiple OpenMP DLLs being loaded in 1 session.  It seems the C# code is calling the libraries and Python doesn't like multiple copies of the same DLL.  Not a huge deal when you know the "fix" I posted above.  This results from just running the examples in the Readme.md for natural gas storage with ratchets.

**Comment by cmdty** [comment]
Hi @mattslezak-shell, thanks for sharing the result and sharing it on here. I'll create an issue to update the documentation as I can't see this being fixed in the code any time soon.

**Comment by cmdty** [comment]
Closing as workaround has been documented and new issue created to fix.
