### ISSUE TITLE
Power Storage Simulation

### ISSUE THREAD

**Issue by tibz64** [cmdty/storage#15]
Hi all,

Thank you for this great job. I am trying to use it to optimize and value power storage facilities hourly, but I am facing two issues. 

1. Cycling constraint: I have to limit the absolute overall amount of energy injected and withdrawn (sum of both) over a period of time, e.g., 24 hrs or a year (8760 hrs). Any idea how I can model it? 

> Example: t1: injection = 1; t2: withdrawing = 1 means the total absolute energy used over the two periods is 2

2. Hourly Forward Curve in the Multifactor model: I have an hourly forward curve, but I do not know how to calibrate the model and which basis function to use since all the examples use a daily curve. Do you know where I can find an example using an hourly power curve?

Thank you for the help

**Comment by cmdty** [comment]
Hi, please email me about this.

**Comment by cmdty** [comment]
For your first question, in summary cycle constraints can’t be done. This would require significant code changes. But I am interested in implementing this if given a detailed spec.
