### ISSUE TITLE
Error with a min_inventory value different from 0

### ISSUE THREAD

**Issue by tibz64** [cmdty/storage#16]
Hi,

I do not manage to run the model since I change the value of the min_inventory... it only works with a value equal to 0.

It throws the following error : 

<InventoryConstraintsCannotBeFulfilledException: Valuation calculation cannot be performed as storage inventory constraints cannot be fulfilled.
   à Cmdty.Storage.StorageHelper.CalculateInventorySpace[T](ICmdtyStorage`1 storage, Double startingInventory, T currentPeriod)
   à Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance)>

You can reproduce the error by using the given python example in the repository  [https://github.com/cmdty/storage#storage-with-time-and-inventory-varying-injectwithdraw-rates](https://github.com/cmdty/storage#storage-with-time-and-inventory-varying-injectwithdraw-rates) and changing the min_inventory value

**Comment by cmdty** [comment]
I think this problem is caused by the following row when creating the CmdtyStorage object:
   .MustBeEmptyAtEnd()

This enforces zero inventory at the end so it is easy to see why this would be non-compatible with a non-zero min inventory. Try removing this line and running the code.

**Comment by tibz64** [comment]
Indeed, it is easy to see why it does not work 👍 Thanks!
