### ISSUE TITLE
storage_gui has injection and withdrawal rate reverse to the ratchet storage definition

### ISSUE THREAD

**Issue by londown** [cmdty/storage#32]
**### In storage_gui.py:**

```
RatchetRow = namedtuple('RatchetRow', ['date', 'inventory', 'inject_rate', 'withdraw_rate'])

def enumerate_ratchets():
    ratchet_row = 0
    while ratchet_row < num_ratch_rows and ratchet_input_sheet.cells[1].value[ratchet_row] != '':
        yield RatchetRow(ratchet_input_sheet.cells[0].value[ratchet_row], ratchet_input_sheet.cells[1].value[ratchet_row],
                         ratchet_input_sheet.cells[2].value[ratchet_row], ratchet_input_sheet.cells[3].value[ratchet_row])
        ratchet_row += 1


def read_ratchets():
    ratchets = []
    for ratchet in enumerate_ratchets():
        if ratchet.date != '':
            dt_item = (pd.Period(ratchet.date, freq=freq), [(ratchet.inventory, -ratchet.inject_rate, ratchet.withdraw_rate)])
            ratchets.append(dt_item)
        else:
            dt_item[1].append((ratchet.inventory, -ratchet.inject_rate, ratchet.withdraw_rate))
    return ratchets
```

**### In creating_storage_instance notebook:**
The second element of the tuple as an iterable of tuples, each with three elements:

The first element is the inventory.
The **second element is the maximum withdrawal rate.**
The **third element is the maximum injection rate.**

I am able to match the results to simple storage by flipping them around in the storage_gui.

**Comment by cmdty** [comment]
Yes, that is correct. When creating a CmdtyStorage instance with ratchets, a negative number in the 3-tuples represents withdrawal. This was motivated by making the API clearer for storage with forced injection and/or withdrawal, by having withdrawal as a negative number makes it clearer this it is withdrawal. For example a 3-tuple of (5000.0, -20.0, -10.0) would be forced withdrawal rate between 20 and 10. The example GUI didn't follow this convention as it is expected to be used by less technical users, so I wanted to make it as easy to use as possible. For ratchets in the GUI a header in the table makes it clear which number is injection or withdrawal, and users don't have to type in a minus sign in the usual case where there isn't forced injection.

**Comment by londown** [comment]
This is not about negative numbers but that in the widget you're creating ratchet object with 
`Date, Inventory, -InjectionRate, WithdrawalRate`
while your documentation states it should be
`Date, Inventory, -WithdrawalRate, InjectionRate`

**Comment by cmdty** [comment]
OK, understood, and that does sound like a bug. I’ll take a look at the weekend.

**Comment by cmdty** [comment]
Crikey, that's a howler of a bug! Should be fixed now. Thanks @londown for spotting and flagging this. Please pull the latest code, check it looks ok for you and then close this issue accordingly.

**Comment by londown** [comment]
Thanks

**Comment by cmdty** [comment]
> Thanks. Can I suggest an additional change to replace lines 185-186
> 
> ```
> for idx, title in enumerate(titles):
>         tab.set_title(idx, title)
> ```
> 
> with `tab.titles = titles`

I tried this and it didn't work. Think it must be because I'm using an older version (7.6.5) of ipywidgets.
