### ISSUE TITLE
Issue installing Cmdty-storage Python (spyder)

### ISSUE THREAD

**Issue by kzawi** [cmdty/storage#8]
HI Team,

i'm having this issue when i try to install python package , i have tried to upgrade pip / wheel / setuptools as well 
however still getting the following error message.

`Collecting cmdty_storage
  Using cached https://files.pythonhosted.org/packages/cc/1e/da3d37c8afb036ef121514515006a32c2d9cf6c35ff4d44f674c8447f220/cmdty_storage-0.1.0a7-py3-none-any.whl
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.6/dist-packages (from cmdty_storage) (1.1.5)
Collecting pythonnet==2.4.0
  Using cached https://files.pythonhosted.org/packages/4a/0a/5964a5a1fdf207fab8e718edd1f8d3578e0681577fe9abe0d9006f9718c2/pythonnet-2.4.0.tar.gz
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->cmdty_storage) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->cmdty_storage) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->cmdty_storage) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->cmdty_storage) (1.15.0)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet, cmdty-storage
    Running setup.py install for pythonnet ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r07633fo/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r07633fo/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-80vpah_w/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

Thank you for your help

**Comment by cmdty** [comment]
It appears you're using Linux, in which case try following the [instructions for the curves package](https://github.com/cmdty/curves#installing-for-python-on-linux) to get this to work.

**Comment by kzawi** [comment]
Hi Team,

i'm not using Linux i'm using windows 10 with Spyder  and python 3.8.5.
Could you please advise ?

**Comment by cmdty** [comment]
I've taken a look and this appears to be related to [the following issue](https://github.com/pythonnet/pythonnet/issues/1017) with pythonnnet v2.4.0 and Python version 3.8. So you'll have to downgrade to Python 3.7.x. The latest version of the pythonnet package don't have this issue. I plan to upgrade the pythonnet dependency with the next release so support for Python 3.8 should be sorted when this is released.

**Comment by cmdty** [comment]
Hi @kzawi this issue should be fixed with an upgrade to pythonnet. I've published [a version to TestPyPI](https://test.pypi.org/project/cmdty-storage/) which dependents on pythonnnet v2.5.1. Try installing this and hopefully it should work with Python 3.8.5. You might have to manually install/upgrade the pyhonnnet dependency package due to this being on TestPyPI.

**Comment by kzawi** [comment]
Hi Team , thank you very much for your prompt answer and your quick update i will try to upgrade pythonnet and see if the issue is fixed.
if there is anything i will revert .

**Comment by cmdty** [comment]
Version 0.1.0, which supports Python 3.4, has now been release on PyPI.
